on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  terraform-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      run: echo "Environment is $ENVIRONMENT"

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Terraform Init
      working-directory: ./terraform # Ensure this matches the directory where your Terraform files are
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform # Ensure this matches the directory where your Terraform files are
      env:
        TF_VAR_environment: ${{ inputs.environment }}
      run: terraform apply -auto-approve
